# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

development:
  adapter: postgresql
  encoding: unicode
  database: ultiteam_dev
  pool: 5
  username: derekstevens
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: ultiteam_test
  pool: 5
  username: derekstevens
  password:


production:
  adapter: postgresql
  encoding: unicode
  database: ultiteam_prod
  pool: 5
  username: derekstevens
  password:
